# =========================================================
# GitHub Actions Workflow - Build, Test, Deploy .NET + Bicep
# =========================================================
name: eShopOnWeb Build and Deploy eastus

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-eshoponweb-eastus3
  LOCATION: eastus
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: a94f2344-3f49-4d2c-801a-53bd6d540d09
  WEBAPP_NAME: eshoponweb-eastus   # nome fixo determinístico

# =========================================================
# Job 1: Build and Test the .NET project
# =========================================================
jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload artifact for deployment job (App)
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload artifact for deployment job (Bicep)
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

# =========================================================
# Job 2: Deploy infrastructure + publish app
# =========================================================
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download artifact from build job (App)
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download artifact from build job (Bicep)
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create Resource Group if not exists
        run: |
          az group create \
            --name ${{ env.RESOURCE_GROUP }} \
            --location ${{ env.LOCATION }} \
            --subscription ${{ env.SUBSCRIPTION_ID }}

      - name: Deploy Azure WebApp via Bicep
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ./bicep-template/webapp.bicep \
            --parameters location=${{ env.LOCATION }} webAppName=${{ env.WEBAPP_NAME }} \
            --mode Incremental

      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            echo "Deploying to ${{ env.WEBAPP_NAME }}"
            az webapp deploy \
              --name ${{ env.WEBAPP_NAME }} \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
