# =========================================================
# GitHub Actions Workflow - Build, Test, Deploy .NET + Bicep
# =========================================================
name: eShopOnWeb Build and Test eastus

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-eshoponweb-eastus2
  LOCATION: eastus
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: a94f2344-3f49-4d2c-801a-53bd6d540d09

# =========================================================
# Job 1: Build and Test the .NET project
# =========================================================
jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'preview'

      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
          cd ${{env.DOTNET_ROOT}}/myapp
          zip -r ../app.zip .

      - name: Upload artifact for deployment job (App)
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/app.zip

      - name: Upload artifact for deployment job (Bicep)
        uses: actions/upload-artifact@v4
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE_FILE }}

# =========================================================
# Job 2: Deploy infrastructure + publish app
# =========================================================
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
      - name: Download artifact from build job (App)
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: .net-app

      - name: Download artifact from build job (Bicep)
        uses: actions/download-artifact@v4
        with:
          name: bicep-template
          path: bicep-template

      - name: List files in bicep-template
        run: ls -R bicep-template

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Azure WebApp via Bicep
        id: deploywebapp
        run: |
          az deployment group create \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --template-file ./bicep-template/webapp.bicep \
            --parameters location=${{ env.LOCATION }} \
            --mode Incremental \
            -o json > deployment-output.json

          # Extract webAppName from Bicep output JSON
          WEBAPP_NAME=$(jq -r '.properties.outputs.webAppName.value' deployment-output.json)
          echo "webAppName=$WEBAPP_NAME" >> $GITHUB_OUTPUT

      - name: Publish Website to WebApp
        uses: Azure/cli@v2
        with:
          inlineScript: |
            APP_NAME="${{ steps.deploywebapp.outputs.webAppName }}"
            echo "Deploying to $APP_NAME"
            az webapp deploy \
              --name $APP_NAME \
              --resource-group ${{ env.RESOURCE_GROUP }} \
              --src-path .net-app/app.zip \
              --type zip
